### ISSUE TITLE
def mark_completed(index)

### ISSUE THREAD

**Issue by joerez** [MakeSchool-Tutorials/Rainbow-Checklist#1]
I really am not sure what I should be doing here.

I would love to do it myself, and I think we should be able to.

Here's my recomendation:

Keep them doing it themselves, but write out the sudo code steps in comments.

We as users can then put in the code underneath the box.

Also please provide what an example output might look like.

Let me know if you have any questions.

**Comment by JSitter** [comment]
Solution is a single line of code. Added hints at where to look for the answer and additional guidance on function requirements.  Sample output also added for clarity.
